// Generated by CoffeeScript 1.7.1
var Marker;

Marker = (function() {
  function Marker(id, latitude, longitude) {
    this.id = id;
    this.latitude = latitude;
    this.longitude = longitude;
    this.start = null;
  }

  return Marker;

})();

this.end = null;

this.icon = "http://mapicons.nicolasmollet.com/wp-content/uploads/mapicons/shape-default/color-66c547/shapecolor-light/shadow-1/border-white/symbolstyle-dark/symbolshadowstyle-no/gradient-no/bridge_old.png";

this.showWindow = false;
