// Generated by CoffeeScript 1.7.1
var Marker, app;

Marker = (function() {
  function Marker(id, latitude, longitude) {
    this.id = id;
    this.latitude = latitude;
    this.longitude = longitude;
    this.start = null;
    this.end = null;
    this.icon = "/states/inactive.png";
    this.prevIcon = "/states/inactive.png";
    this.showWindow = false;
  }

  return Marker;

})();

app = angular.module('mapApp', ['google-maps', 'services']);

app.controller('infoController', [
  '$scope', 'sharedProperties', function($scope, sharedProperties) {
    $scope.onStartClick = function() {
      return sharedProperties.setStart($scope.model.id);
    };
    $scope.onEndClick = function() {
      return sharedProperties.setEnd($scope.model.id);
    };
    return $scope.onStreetViewClick = function() {
      var currentId, gMap, lat, lng, map, panorama, properties;
      currentId = $scope.model.id;
      properties = sharedProperties.Properties();
      console.log(properties);
      map = properties.panorama;
      gMap = map.getGMap();
      panorama = gMap.getStreetView();
      lat = properties.markers[currentId].latitude;
      lng = properties.markers[currentId].longitude;
      panorama.setPosition(new google.maps.LatLng(lat, lng));
      panorama.setVisible(true);
      return sharedProperties.setPanorama(map);
    };
  }
]);

app.controller('mapController', [
  '$scope', 'sharedProperties', function($scope, sharedProperties) {
    var latlngs, setMarkerToEnd, setMarkerToInactive, setMarkerToStart;
    $scope.markers = [];
    $scope.map = {
      'center': {
        'latitude': 33.884388,
        'longitude': -117.641235
      },
      'zoom': 12
    };
    $scope.streetView = {};
    $scope.local = sharedProperties.Properties();
    $scope.showTraffic = false;
    $scope.toggleTrafficLayer = function() {
      return $scope.showTraffic = !$scope.showTraffic;
    };
    setMarkerToStart = function(marker) {
      if (marker == null) {
        return;
      }
      marker.status = "start";
      marker.icon = "/states/startpoint.png";
      return marker.prevIcon = "/states/startpoint.png";
    };
    setMarkerToInactive = function(marker) {
      if (marker == null) {
        return;
      }
      marker.status = "inactive";
      marker.icon = "/states/inactive.png";
      return marker.prevIcon = "/states/inactive.png";
    };
    setMarkerToEnd = function(marker) {
      if (marker == null) {
        return;
      }
      marker.status = "end";
      marker.icon = "/states/endpoint.png";
      return marker.prevIcon = "/states/endpoint.png";
    };
    latlngs = [];
    latlngs.push({
      'latitude': 33.843801,
      'longitude': -117.717234
    });
    latlngs.push({
      'latitude': 33.826690,
      'longitude': -117.716419
    });
    latlngs.push({
      'latitude': 33.820415,
      'longitude': -117.716977
    });
    latlngs.forEach(function(element, index) {
      var marker;
      marker = new Marker(index, element.latitude, element.longitude);
      marker.close = function() {
        this.model.icon = marker.prevIcon;
        this.model.showWindow = false;
        return $scope.$apply();
      };
      marker.onClick = function() {
        this.model.status = "focused";
        sharedProperties.setPanorama($scope.streetView);
        console.log($scope.streetView);
        $scope.local.markers.forEach(function(element) {
          element.showWindow = false;
          return element.icon = element.prevIcon;
        });
        this.model.icon = "/states/focused.png";
        this.model.showWindow = true;
        $scope.id = this.model.id;
        return $scope.$apply();
      };
      return $scope.local.markers.push(marker);
    });
    return $scope.$watchCollection('local.route', function(newValues, oldValues, scope) {
      var endId, markers, startId;
      if (newValues == null) {
        return;
      }
      startId = newValues.start;
      endId = newValues.end;
      if ((startId === -1) && (endId === -1) || (startId === endId)) {
        return;
      }
      markers = sharedProperties.Properties().markers;
      markers.forEach(function(marker) {
        if (marker.status === "start" || marker.status === "end") {
          return setMarkerToInactive(marker);
        }
      });
      sharedProperties.setMarkers(markers);
      setMarkerToStart(markers[startId]);
      return setMarkerToEnd(markers[endId]);
    });
  }
]);
