// Generated by CoffeeScript 1.5.0
(function() {
  var app;

  app = angular.module('mapApp', ['google-maps']);

  app.controller('infoController', [
    '$scope', function($scope) {
      $scope.init = function(id) {
        $scope.id = $scope.$parent.id;
        return console.log($scope.$parent.id);
      };
      $scope.onStartClick = function() {
        console.log("Start at " + $scope.model.id);
        $scope.local.start = $scope.model.id;
        return $scope.model.icon = "http://mapicons.nicolasmollet.com/wp-content/uploads/mapicons/shape-default/color-262626/shapecolor-white/shadow-1/border-color/symbolstyle-color/symbolshadowstyle-no/gradient-no/bridge_old.png";
      };
      return $scope.onEndClick = function() {
        console.log("Ends at " + $scope.model.id);
        console.log($scope.map);
        $scope.$parent.local.end = $scope.model.id;
        console.log($scope);
        return $scope.model.icon = "http://mapicons.nicolasmollet.com/wp-content/uploads/mapicons/shape-default/color-262626/shapecolor-color/shadow-1/border-dark/symbolstyle-white/symbolshadowstyle-dark/gradient-no/bridge_old.png";
      };
    }
  ]);

  app.controller('mapController', [
    '$scope', function($scope) {
      var i, latlng, latlngs, marker, _i, _len, _results;
      $scope.markers = [];
      $scope.map = {
        'center': {
          'latitude': 33.884388,
          'longitude': -117.641235
        },
        'zoom': 12
      };
      $scope.local = {};
      $scope.local.start = 0;
      $scope.local.end = 0;
      latlngs = [];
      latlngs.push({
        'latitude': 33.884780,
        'longitude': -117.639754
      });
      latlngs.push({
        'latitude': 33.884388,
        'longitude': -117.641235
      });
      latlngs.push({
        'latitude': 33.883924,
        'longitude': -117.643724
      });
      _results = [];
      for (i = _i = 0, _len = latlngs.length; _i < _len; i = ++_i) {
        latlng = latlngs[i];
        marker = {};
        marker.start = 0;
        marker.end = 0;
        marker.latitude = latlng.latitude;
        marker.longitude = latlng.longitude;
        marker.id = i;
        marker.icon = "http://mapicons.nicolasmollet.com/wp-content/uploads/mapicons/shape-default/color-66c547/shapecolor-light/shadow-1/border-white/symbolstyle-dark/symbolshadowstyle-no/gradient-no/bridge_old.png";
        marker.showWindow = false;
        marker.close = function() {
          this.model.showWindow = false;
          return $scope.$apply();
        };
        marker.onClick = function() {
          var markerr, _j, _len1, _ref;
          _ref = $scope.markers;
          for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
            markerr = _ref[_j];
            markerr.showWindow = false;
          }
          this.model.showWindow = true;
          $scope.id = this.model.id;
          return $scope.$apply();
        };
        _results.push($scope.markers.push(marker));
      }
      return _results;
    }
  ]);

}).call(this);
