// Generated by CoffeeScript 1.7.1
var app;

app = angular.module('services', []);

app.service('sharedProperties', function() {
  var props;
  props = {
    route: {
      start: -1,
      end: -1
    },
    markers: [],
    panorama: {}
  };
  return {
    Properties: function() {
      return props;
    },
    setStart: function(val) {
      return props.route.start = val;
    },
    setEnd: function(val) {
      return props.route.end = val;
    },
    setMarkers: function(val) {
      return props.markers = val;
    },
    setPanorama: function(val) {
      return props.panorama = val.getGMap().getStreetView();
    }
  };
});

app.service('markerService', function() {
  return {
    setMarkerStatus: function(marker, status) {
      if (marker == null) {

      } else {
        marker.status = status;
        if (status === 'focused') {
          marker.showWindow = true;
        }
        if (status !== 'focused') {
          marker.prevIcon = "/vitaliikalinincrg/map-test//states/" + status + ".png";
        }
        return marker.icon = "/vitaliikalinincrg/map-test//states/" + status + ".png";
      }
    },
    setMarkerDefault: function(marker) {
      marker.showWindow = false;
      return marker.icon = marker.prevIcon;
    }
  };
});
